export default{
    SET_GIFS: 'SET_GIFS',
    ADD_FAVOURITE: 'ADD_FAVOURITE',
    REMOVE_FAVOURITE: 'REMOVE_FAVOURITE',
    SET_FAVOURITES: 'SET_FAVOURITES',
    REMOVE_FAVOURITES: 'REMOVE_FAVOURITES',
    REGISTER_USER: 'REGISTER_USER',
    DELETE_USER: 'DELETE_USER',
    GET_CURRENT_USER: 'SET_CURRENT_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SET_ERROR: 'SET_ERROR'
};