export default{
    ADD_FAVOURITE: 'ADD_FAVOURITE',
    REMOVE_FAVOURITE: 'REMOVE_FAVOURITE',
    GET_ALL_FAVOURITES: 'GET_ALL_FAVOURITES',
    REMOVE_ALL_FAVOURITES: 'REMOVE_ALL_FAVOURITES',
    REGISTER_USER: 'REGISTER_USER',
    DELETE_USER: 'DELETE_USER',
    GET_CURRENT_USER: 'GET_CURRENT_USER',
    UPDATE_USER: 'UPDATE_USER',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    SET_ERROR: 'SET_ERROR'
};