export default{
    SET_GIFS: 'SET_GIFS',
    SET_FAVOURITES: 'SET_FAVOURITES',
    SET_ERROR: 'SET_ERROR',
    SET_USER: 'SET_USER',
    ADD_GIF: 'ADD_GIF',
    DELETE_GIF: 'DELETE_GIF',
    ADD_GRAPHQL_ERROR: 'ADD_GRAPHQL_ERROR',
    SAVE_TOKEN: 'SAVE_TOKEN',
    SET_USER_LOADED: 'SET_USER_LOADED',

};